### ISSUE TITLE
.NET 4.8 WPF UserControl Hosted in Winform - NullReferenceException

### ISSUE THREAD

**Issue by adamrgointerject** [microsoft/dotnet#1041]
After installing .NET 4.8 and testing our Excel COM add-in (upgraded from .NET 4.0) with it I found that there is a bug related to a WPF UserControl being hosted in a WinForm using ElementHost. I first thought the behavior may be related to being a COM add-in rather than a desktop application, but I was able to recreate the bug with a desktop application (example solution to recreate bug is attached).

**Scenario to Cause Bug**
The below code creates a `Form` that has a `ElementHost` and shows the form:
```vb
Dim newForm As FormHostingWPF = New FormHostingWPF()
newForm.InitializeForm()
newForm.Show()
```

In FormHostingWPF.vb the `InitializeForm()` will create the WPF `UserControl` and set it to the `Form`s `ElementHost.Child` 
```vb
Friend Sub InitializeForm()
    Dim wpfControl As New WPFChild()
    wpfControl.Form = Me ' The control has a reference to Form so it can close it on button click

    ElementHost1.Child = wpfControl
End Sub
```

In `WPFChild` there is a Button and the click event is wired up to close the form hosting it. code below:
```vb
Private Sub Button_Click(sender As Object, e As Windows.RoutedEventArgs)
    If Me.Form IsNot Nothing Then Me.Form.Close()
End Sub
```

**When you press 'Tab' to give the button focus and press 'Enter' key to click the button (which closes the `Form`) the program will crash. Here is the stack trace from the exception:**
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=WindowsFormsIntegration
  StackTrace:
   at System.Windows.Forms.Integration.ElementHost.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FPreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   at RecreateElementHostProcessCmdKeyBug.My.MyApplication.Main(String[] Args) in :line 81
```

**NOTE:** This exception is not thrown when using `ShowDialog()` e.g...
```vb
Using newForm As FormHostingWPF = New FormHostingWPF()
    newForm.InitializeForm()
    newForm.ShowDialog()
End Using
```

I was hoping to upgrade our application to .NET 4.8, but this bug is preventing us from committing to .NET 4.8. Is there any possible work around to this?

**Attached Solution To Recreate Bug:** [RecreateElementHostProcessCmdKeyBug.zip](https://github.com/microsoft/dotnet/files/3193110/RecreateElementHostProcessCmdKeyBug.zip)

**Comment by vatsan-madhavan** [comment]
Let's use https://github.com/microsoft/dotnet-framework-early-access/issues/62 as the main investigation thread.

**Comment by M-Lipin** [comment]
The issue has been fixed in 899206 and the fix should be available in the latest .NET 4.8.
