### ISSUE TITLE
Convert.ToDecimal generate exception on Linux

### ISSUE THREAD

**Issue by enricobenedos** [microsoft/dotnet#1237]
Good Morning,

I've a .NET CORE API hosted on a Linux environment. My develop machine has macOS as OS.
The same code executed on my machine works perfectly but on the Linux environment it generate an exception when trying to convert a decimal number
```log
System.OverflowException: Value was either too large or too small for a Decimal.
at System.Number.ThrowOverflowException(TypeCode type)
at System.Decimal.DecCalc.VarDecFromR8(Double input, DecCalc& result)
at WamiiApi.Controllers.ToursController.PostTours(Tours tours) in /home/wamii/wamii_api_v2/WamiiApi/Controllers/ToursController.cs:line 156
at lambda_method(Closure , Object )
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
```

I tried to print this number on my Mac console using Visual Studio and it's value is `58.0159311212281`.
I think it is not a normal behaviour

**Comment by enricobenedos** [comment]
Wrong repo. Need to fill it on netcore one
