### ISSUE TITLE
Pipes cannot be enumerated in Windows 10 Insider Preview

### ISSUE THREAD

**Issue by ArtemAvramenko** [Microsoft/dotnet#338]
The following code (C#) should return all pipes on a machine:
```
Directory.GetFiles(@"\\.\pipe\")
```
But it fails in Windows 10 (OS build 14959, .NET 4.6.2.395222):

```
System.IO.IOException: The parameter is incorrect.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
```

All works fine in Windows XP, Vista, 7, 8 , 8.1, 10 (build 14931)

If it is not a .NET Framework bug, please redirect it to the appropriate team.

**Comment by danmosemsft** [comment]
Using .NET Framework and .NET Core on 14393.577 I get 
`Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\pipe'.`
