### ISSUE TITLE
dotnet migrate crashes with System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by xapienz** [Microsoft/dotnet#355]
Hello,
I'm trying to migrate the project.json-style project to csproj.
For this I'm using the command `dotnet migrate`, but get the following output:
```
Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include command-line arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.

Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 3800 ms
Expanding 100% 31126 ms
Migration failed.

Unhandled Exception: System.UnauthorizedAccessException: Access to the path '/home/username/.wine/dosdevices/z:/snap/core/1240/var/spool/rsyslog' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.UnixFileSystem.FileSystemEnumerable`1.OpenDirectory(String fullPath)
   at System.IO.UnixFileSystem.FileSystemEnumerable`1.<Enumerate>d__11.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.IO.DirectoryInfo.InternalGetDirectories(String searchPattern, SearchOption searchOption)
   at System.IO.DirectoryInfo.GetDirectories(String searchPattern, SearchOption searchOption)
   at Microsoft.DotNet.ProjectJsonMigration.ProjectDependencyFinder.GetPotentialProjects(IEnumerable`1 searchPaths)
   at Microsoft.DotNet.ProjectJsonMigration.ProjectDependencyFinder.FindPossibleProjectDependencies(SlnFile slnFile, String projectJsonFilePath)
   at Microsoft.DotNet.ProjectJsonMigration.ProjectDependencyFinder.ResolveDirectProjectDependenciesForFramework(Project project, NuGetFramework framework, IEnumerable`1 preResolvedProjects, SlnFile solutionFile)
   at Microsoft.DotNet.ProjectJsonMigration.ProjectDependencyFinder.ResolveAllProjectDependenciesForFramework(ProjectDependency projectToResolve, NuGetFramework framework, IEnumerable`1 preResolvedProjects, SlnFile solutionFile)
   at Microsoft.DotNet.ProjectJsonMigration.Rules.MigrateProjectDependenciesRule.MigrateProjectJsonProjectDependency(Project project, NuGetFramework framework, HashSet`1 migratedXProjDependencyNames, SlnFile solutionFile, ProjectRootElement outputMSBuildProject)
   at Microsoft.DotNet.ProjectJsonMigration.Rules.MigrateProjectDependenciesRule.MigrateProjectJsonProjectDependencies(IEnumerable`1 projectContexts, HashSet`1 migratedXProjDependencyNames, SlnFile solutionFile, ProjectRootElement outputMSBuildProject)
   at Microsoft.DotNet.ProjectJsonMigration.Rules.MigrateProjectDependenciesRule.Apply(MigrationSettings migrationSettings, MigrationRuleInputs migrationRuleInputs)
   at Microsoft.DotNet.ProjectJsonMigration.DefaultMigrationRuleSet.Apply(MigrationSettings migrationSettings, MigrationRuleInputs migrationRuleInputs)
   at Microsoft.DotNet.ProjectJsonMigration.ProjectMigrator.MigrateProject(MigrationSettings migrationSettings)
   at Microsoft.DotNet.ProjectJsonMigration.ProjectMigrator.Migrate(MigrationSettings rootSettings, Boolean skipProjectReferences)
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.Execute()
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.<>c__DisplayClass35_0.<Run>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Аварийный останов (сделан дамп памяти)
```

It fails while studying the contents of ~/.wine.
Why does it try to iterate over all directories in home dir?

I'm using dotnet-dev-1.0.0-rc4-004771.

**Comment by richlander** [comment]
Are you running .NET Core under Wine? The directory name looks very odd. Have you tried on just Windows or Linux?

/cc @blackdwarf

**Comment by xapienz** [comment]
No, I'm running .NET Core directly in Linux.
The problem happens if project directory is inside homedir. In this case `dotnet migrate` tries to read everything which is localed in homedir, including .wine, which contains symlinks that point to root filesystem.

**Comment by xapienz** [comment]
As an example, you may try to reproduce the problem using following steps:
```bash
# creating directory without read permission in homedir:
mkdir ~/deny
chmod -r ~/deny
# creating project.json-based project:
mkdir ~/test
cd ~/test
echo "{ 'frameworks': { 'netcoreapp1.0': {} } }" > project.json
# trying to convert it to csproj:
dotnet migrate
```

After this you will get:
```bash
$ dotnet migrate
Migration failed.

Unhandled Exception: System.UnauthorizedAccessException: Access to the path '/home/username/deny' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
```

**Comment by richlander** [comment]
Ah, I understand now. I've never tried that.

Thoughts, @blackdwarf @livarcocc??

**Comment by livarcocc** [comment]
Could you move your project into a new subfolder? This happens because Migration looks at the folder containing your project to try to find dependencies and other files that may influence your project. And, on this case, you happen to have a folder that is not accessible.

**Comment by richlander** [comment]
Assuming the workaround works (which I expect it will), I propose we close this issue and open a bug on CLI to provide a better experience in this case.

**Comment by xapienz** [comment]
Yes, it works if I move the directory to some subdir. 
But I don't understand, why it would look for dependencies, if they are not set inside project file

**Comment by mormegil-cz** [comment]
I ran into the same issue right now when opening an older solution in VS 15.3.1. The auto-migration failed with _Failed to migrate XProj project_, and _Migration failed. Unhandled Exception: System.UnauthorizedAccessException: Access to the path 'Y:\System Volume Information' is denied_, as the project was in a directory under a drive root (e.g. `Y:\Dir\Project.sln`). Moving to a subfolder temporarily and migrating worked fine. However, I don’t see a reason which it should die in such case. (I am not even sure why it needs to sniff around, but crashing when a folder is inaccessible, that seems really silly.)
