### ISSUE TITLE
.net 4.6.2  signedXml.CheckSignature(); problem with rsa2

### ISSUE THREAD

**Issue by zchpit** [Microsoft/dotnet#430]
After upgrade to .net 4.6.2 I have problem with signedXml.CheckSignature(); with RSA2

For signing I use
CryptoConfig.AddAlgorithm(typeof(RSAPKCS1SHA256SignatureDescription), "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256");

It works on my machine but don't work on test serwer. Error:

System.Security.Cryptography.CryptographicException SignatureDescription could not be created for the signature algorithm supplied.
at System.Security.Cryptography.Xml.SignedXml.CheckSignedInfo(AsymmetricAlgorithm key)
at System.Security.Cryptography.Xml.SignedXml.CheckSignature(AsymmetricAlgorithm key)
at System.Security.Cryptography.Xml.SignedXml.CheckSignatureReturningKey(AsymmetricAlgorithm& signingKey)
at ePR.Biz.Security.Signature.Veryfier.EprDsigSimpleVerifier.VerifyXml(XmlDocument doc, X509Certificate2& cert)
at ePR.Biz.Security.Signature.Veryfier.EprDsigSimpleVerifier.Verify(FileContentInfo fci, X509Certificate2& cert, String& stringSignature)
at ePR.Biz.Security.Signature.SignatureManager.ValidateSignatureCore(ISignatureVeryfier veryfier, FileContentInfo fci)
at ePR.Biz.Security.Signature.SignatureManager.ValidateSignature(XmlDocument doc)

P.S. In my comuper I work as administator and run as Console App., in test serwer there is custom profile created and run as a Windows Service

**Comment by zchpit** [comment]
Before 4.6.2 it was working in .net 4.5

**Comment by richlander** [comment]
@karelz who should look at this?

/cc @preetikr

**Comment by karelz** [comment]
This issue was moved to dotnet/corefx#21539

**Comment by richlander** [comment]
Thanks for looking at this issue w/rt to .NET Core. We'll keep this open for .NET Framework.

@zchpit is this similar to #341?

**Comment by ianhays** [comment]
closing per Jeremy's analysis in https://github.com/dotnet/corefx/issues/21539
