### ISSUE TITLE
System.OverflowException in PresentationFramework.dll in System.Windows.Shell.WindowChromeWorker

### ISSUE THREAD

**Issue by contre** [microsoft/dotnet#689]
We have been getting a crash when using the mouse on certain windows in our WPF application. This Stackoverflow issue appears with exactly the same error messages as our own so I believe it to be relevant. https://stackoverflow.com/questions/33287542/what-would-cause-wm-nchittest-lparam-to-overflow-a-32-bit-integer

This issue has also been reported to the Visual Studio community site and a simple test application has been provided. https://developercommunity.visualstudio.com/content/problem/167357/overflow-exception-in-windowchrome.html

The crashes occur on a Windows 10 Pro Version 1709 OS Build 16299.309

We are targeting .NET 4.6.2 with our application. If there is any other information that I can provide, please let me know.

The exception info, on my computer, is as follows:
```
System.OverflowException
  HResult=0x80131516
  Message=Arithmetic operation resulted in an overflow.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Shell.WindowChromeWorker._HandleNCHitTest(WM uMsg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Shell.WindowChromeWorker._WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by kalaskarsanket** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
