### ISSUE TITLE
DataGridView ArgumentException

### ISSUE THREAD

**Issue by nnpcYvIVl** [microsoft/dotnet#718]
To cause the crash wait for two rows to appear on screen, click and hold the bottom of the second row header (as if resizing the row), wait for the second row to disappear, release mouse button.

```
System.ArgumentOutOfRangeException occurred
Message=Index was out of range.Must be non-negative and less than the size of the collection.
Source= mscorlib
StackTrace:
 at System.Collections.ArrayList.get_Item(Int32 index)
 at System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
 at System.Windows.Forms.DataGridView.EndRowResize(MouseEventArgs e)
 at System.Windows.Forms.DataGridView.OnMouseUp(MouseEventArgs e)
```

```csharp
using System;
using System.ComponentModel;
using System.Linq;
using System.Windows.Forms;

namespace DataGridViewBugs
{
    static class Program
    {
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new DataGridViewArgumentExceptionBugForm());
        }
    }

    public class DataGridViewArgumentExceptionBugForm : Form
    {
        DataGridView datagridview = new DataGridView() { Dock = DockStyle.Fill };
        BindingSource bindingsource = new BindingSource();
        Timer timer = new Timer();

        static int maxrows = 2;

        int rowcount = maxrows;

        bool ascending = false;

        public DataGridViewArgumentExceptionBugForm()
        {
            this.Size = new System.Drawing.Size(300, 300);

            this.Controls.Add(datagridview);

            ToggleDataGridViewRows();

            timer.Interval = 1500;
            timer.Enabled = true;
            timer.Tick += timer_Tick;
        }

        private void timer_Tick(object sender, EventArgs e)
        {
            ToggleDataGridViewRows();
        }

        private void ToggleDataGridViewRows()
        {
            string[] stringlist = new string[] { };

            if (rowcount == maxrows - 1)
            {
                ascending = true;
            }
            else if (rowcount == maxrows)
            {
                ascending = false;
            }

            if (ascending)
            {
                rowcount = rowcount + 1;
            }
            else
            {
                rowcount = rowcount - 1;
            }

            if (rowcount > 0)
            {
                Array.Resize<string>(ref stringlist, rowcount);
                BindingList<string> newlist = new BindingList<string>((stringlist).ToList());
                bindingsource.DataSource = newlist;
                datagridview.DataSource = bindingsource;
            }
        }
    }
}
```

**Comment by kalaskarsanket** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
