### ISSUE TITLE
After Docker image update to microsoft/dotnet:2.1-sdk. Receicing System.IO.IOException: Method not found: 'System.Memory`1<!0>  

### ISSUE THREAD

**Issue by jdwilly2001** [Microsoft/dotnet#738]
The application was running last week, and now is failing. I am attempting to buidl the docker image with the same code that was confirmed running and now I cannot get the application to serve a basic healthcheck url. Are there any issues with the published 2.1-sdk image?

info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
      Connection id "0HLDKUV7FGMOP" communication error.
System.IO.IOException: Method not found: 'System.Memory`1<!0> System.Memory`1.CreateFromPinnedArray(!0[], Int32, Int32)'. ---> System.MissingMethodException: Method not found: 'System.Memory`1<!0> System.Memory`1.CreateFromPinnedArray(!0[], Int32, Int32)'.
   at System.Buffers.MemoryPoolBlock..ctor(SlabMemoryPool pool, MemoryPoolSlab slab, Int32 offset, Int32 length)
   at System.Buffers.SlabMemoryPool.AllocateSlab()
   at System.Buffers.SlabMemoryPool.Lease()
   at System.IO.Pipelines.Pipe.AllocateWriteHeadUnsynchronized(Int32 sizeHint)
   at System.IO.Pipelines.Pipe.GetMemory(Int32 sizeHint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   --- End of inner exception stack trace ---

**Comment by anandtpatel** [comment]
microsoft/dotnet 2.1-sdk image was working fine on Friday(May 4th). Started giving above error since yesterday(May 7).
