### ISSUE TITLE
Error The type ... exists in both ... and ...

### ISSUE THREAD

**Issue by rst0git** [Microsoft/dotnet#786]
Hello,
I when I start ASP.Net web application from command line with 
```
dotnet build
dotnet run --launch-profile Development --framework netcoreapp2.1 --project SiteTemplate/SiteTemplate.Core/SiteTemplate.Core.csproj
```
It fails with 
```
Now listening on: http://[::]:5000
Now listening on: http://0.0.0.0:5000
Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
h3pwzqd5.1bg(5,62): error CS0433: The type 'RazorViewAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
h3pwzqd5.1bg(33,105): error CS0433: The type 'RazorPage<TModel>' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
h3pwzqd5.1bg(64,67): error CS0115: '_Views_ChartPublic_ChartPublicHomeIndex_Index.ExecuteAsync()': no suitable method found to override
h3pwzqd5.1bg(268,58): error CS0433: The type 'RazorInjectAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
h3pwzqd5.1bg(270,58): error CS0433: The type 'RazorInjectAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
h3pwzqd5.1bg(272,58): error CS0433: The type 'RazorInjectAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
h3pwzqd5.1bg(274,58): error CS0433: The type 'RazorInjectAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
h3pwzqd5.1bg(276,58): error CS0433: The type 'RazorInjectAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
h3pwzqd5.1bg(57,135): error CS0103: The name 'StartTagHelperWritingScope' does not exist in the current context
h3pwzqd5.1bg(57,163): error CS0103: The name 'EndTagHelperWritingScope' does not exist in the current context
h3pwzqd5.1bg(66,13): error CS0103: The name 'BeginContext' does not exist in the current context
h3pwzqd5.1bg(67,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
h3pwzqd5.1bg(68,13): error CS0103: The name 'EndContext' does not exist in the current context
h3pwzqd5.1bg(69,13): error CS0103: The name 'BeginContext' does not exist in the current context
h3pwzqd5.1bg(70,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
h3pwzqd5.1bg(71,13): error CS0103: The name 'EndContext' does not exist in the current context
h3pwzqd5.1bg(72,13): error CS0103: The name 'BeginContext' does not exist in the current context
h3pwzqd5.1bg(73,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
h3pwzqd5.1bg(74,13): error CS0103: The name 'EndContext' does not exist in the current context
h3pwzqd5.1bg(75,13): error CS0103: The name 'DefineSection' does not exist in the current context
h3pwzqd5.1bg(149,13): error CS0103: The name 'BeginContext' does not exist in the current context
h3pwzqd5.1bg(150,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
h3pwzqd5.1bg(151,13): error CS0103: The name 'EndContext' does not exist in the current context
h3pwzqd5.1bg(158,13): error CS0103: The name 'BeginContext' does not exist in the current context
h3pwzqd5.1bg(159,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
h3pwzqd5.1bg(160,13): error CS0103: The name 'EndContext' does not exist in the current context
h3pwzqd5.1bg(161,13): error CS0103: The name 'BeginContext' does not exist in the current context
h3pwzqd5.1bg(165,51): error CS0103: The name 'CreateTagHelper' does not exist in the current context
h3pwzqd5.1bg(172,13): error CS0103: The name 'Write' does not exist in the current context
h3pwzqd5.1bg(174,13): error CS0103: The name 'EndContext' does not exist in the current context
h3pwzqd5.1bg(175,13): error CS0103: The name 'BeginContext' does not exist in the current context
h3pwzqd5.1bg(176,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
h3pwzqd5.1bg(177,13): error CS0103: The name 'EndContext' does not exist in the current context
h3pwzqd5.1bg(178,13): error CS0103: The name 'BeginContext' does not exist in the current context
h3pwzqd5.1bg(180,17): error CS0103: The name 'BeginContext' does not exist in the current context
h3pwzqd5.1bg(181,17): error CS0103: The name 'WriteLiteral' does not exist in the current context
h3pwzqd5.1bg(182,17): error CS0103: The name 'EndContext' does not exist in the current context
h3pwzqd5.1bg(188,17): error CS0103: The name 'BeginContext' does not exist in the current context
h3pwzqd5.1bg(189,17): error CS0103: The name 'WriteLiteral' does not exist in the current context
h3pwzqd5.1bg(190,17): error CS0103: The name 'EndContext' does not exist in the current context
h3pwzqd5.1bg(191,17): error CS0103: The name 'BeginContext' does not exist in the current context
h3pwzqd5.1bg(195,59): error CS0103: The name 'CreateTagHelper' does not exist in the current context
h3pwzqd5.1bg(202,17): error CS0103: The name 'Write' does not exist in the current context
h3pwzqd5.1bg(204,17): error CS0103: The name 'EndContext' does not exist in the current context
h3pwzqd5.1bg(205,17): error CS0103: The name 'BeginContext' does not exist in the current context
h3pwzqd5.1bg(206,17): error CS0103: The name 'WriteLiteral' does not exist in the current context
h3pwzqd5.1bg(207,17): error CS0103: The name 'EndContext' does not exist in the current context
h3pwzqd5.1bg(213,17): error CS0103: The name 'BeginContext' does not exist in the current context
h3pwzqd5.1bg(214,17): error CS0103: The name 'WriteLiteral' does not exist in the current context
h3pwzqd5.1bg(215,17): error CS0103: The name 'EndContext' does not exist in the current context
h3pwzqd5.1bg(216,17): error CS0103: The name 'BeginContext' does not exist in the current context
h3pwzqd5.1bg(220,60): error CS0103: The name 'CreateTagHelper' does not exist in the current context
h3pwzqd5.1bg(227,17): error CS0103: The name 'Write' does not exist in the current context
h3pwzqd5.1bg(229,17): error CS0103: The name 'EndContext' does not exist in the current context
h3pwzqd5.1bg(230,17): error CS0103: The name 'BeginContext' does not exist in the current context
h3pwzqd5.1bg(231,17): error CS0103: The name 'WriteLiteral' does not exist in the current context
h3pwzqd5.1bg(232,17): error CS0103: The name 'EndContext' does not exist in the current context
h3pwzqd5.1bg(233,17): error CS0103: The name 'BeginContext' does not exist in the current context
h3pwzqd5.1bg(237,61): error CS0103: The name 'CreateTagHelper' does not exist in the current context
h3pwzqd5.1bg(244,17): error CS0103: The name 'Write' does not exist in the current context
h3pwzqd5.1bg(246,17): error CS0103: The name 'EndContext' does not exist in the current context
h3pwzqd5.1bg(247,17): error CS0103: The name 'BeginContext' does not exist in the current context
h3pwzqd5.1bg(248,17): error CS0103: The name 'WriteLiteral' does not exist in the current context
h3pwzqd5.1bg(249,17): error CS0103: The name 'EndContext' does not exist in the current context
h3pwzqd5.1bg(252,62): error CS0103: The name 'CreateTagHelper' does not exist in the current context
h3pwzqd5.1bg(260,13): error CS0103: The name 'Write' does not exist in the current context
h3pwzqd5.1bg(262,13): error CS0103: The name 'EndContext' does not exist in the current context
h3pwzqd5.1bg(263,13): error CS0103: The name 'BeginContext' does not exist in the current context
h3pwzqd5.1bg(264,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
h3pwzqd5.1bg(265,13): error CS0103: The name 'EndContext' does not exist in the current context
/Views/ChartPublic/ChartPublicHomeIndex/Index.cshtml(20,2): error CS1929: '_Views_ChartPublic_ChartPublicHomeIndex_Index' does not contain a definition for 'SetPageTitle' and the best extension method overload 'ViewDataExtensions.SetPageTitle(RazorPage, string)' requires a receiver of type 'RazorPage'
/Views/ChartPublic/ChartPublicHomeIndex/Index.cshtml(27,96): error CS0103: The name 'Model' does not exist in the current context
/Views/ChartPublic/ChartPublicHomeIndex/Index.cshtml(31,96): error CS0103: The name 'Model' does not exist in the current context
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromPath(String executingFilePath, String pagePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.GetView(String executingFilePath, String viewPath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.GetView(String executingFilePath, String viewPath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Any ideas what could be the reason for this?

**Comment by rst0git** [comment]
Solved by doing DB drop/migrate
