### ISSUE TITLE
Random System.AccessViolationException

### ISSUE THREAD

**Issue by gli27** [Microsoft/dotnet#795]
Hello team,

I met random below exception. I don't know why the exception will be thrown. 
Application: NewConsole.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.NativeWindow.DefWndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.DefWndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.WmCommand(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ComboBox.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application.Run(System.Windows.Forms.Form)
   at Slb.Horizon.NewUIFramework.NewConsole.Main(System.String[])

**Comment by jnm2** [comment]
Can you provide a sample project?

**Comment by jnm2** [comment]
This doesn't look familiar to me, so I have no clue. In this type of situation, I usually copy my entire test project and delete half of it and see if it still repros. If not, I know part of the the repro is in the part I deleted, and I keep deleting roughly by halves until I figure out what is essential to the repro.

I don't see NUnit in your call stack anywhere. Is this strictly NUnit-related?

**Comment by gli27** [comment]
I think it isn't NUnit. Because it is random in a complex project, I'd like looking for some clue.

**Comment by jnm2** [comment]
I'd be happy to help, but I have no clue. The best advice I can give is to just start deleting everything you possibly can while keeping still reproducing the problem.
Sadly, this forum isn't a super appropriate place for non-NUnit issues. I'd be happy to hear from you via the email in my GitHub profile if you get stuck boiling down the problem.

**Comment by jnm2** [comment]
@gli27 Oh dear! I mixed up which repository this tab was for, I'm sorry! 😆 Yeah, sorry I don't have any clues. If you delete as much as possible and post that code, that gives folks something to work with.
