### ISSUE TITLE
System.OverflowException in System.IO.Packaging.Package.Open

### ISSUE THREAD

**Issue by matteofabbri** [Microsoft/dotnet#818]
Scenario: we have a directory full of files that periodically should be added to a zip package.
On the first round anything runs perfectly, the package is created and all files are added.
Many other rounds runs perfectly and the result package is not to big (around 200MB) then suddenly an overflow exception is raised when the package is open another time.
Surprisingly the package is not corrupted and can be explored in Windows and all files can be extracted and read perfectly.

Stack trace:

System.OverflowException: Arithmetic operation resulted in an overflow.
   at MS.Internal.IO.Zip.ZipIOExtraField.ParseRecord(BinaryReader reader, ZipIOZip64ExtraFieldUsage zip64extraFieldUsage, UInt16 expectedExtraFieldSize)
   at MS.Internal.IO.Zip.ZipIOCentralDirectoryFileHeader.ParseRecord(BinaryReader reader, Encoding encoding)
   at MS.Internal.IO.Zip.ZipIOCentralDirectoryBlock.ParseRecord(BinaryReader reader, Int64 centralDirectoryOffset, Int32 centralDirectoryCount, Int64 expectedCentralDirectorySize)
   at MS.Internal.IO.Zip.ZipIOCentralDirectoryBlock.SeekableLoad(ZipIOBlockManager blockManager)
   at MS.Internal.IO.Zip.ZipIOBlockManager.get_CentralDirectoryBlock()
   at MS.Internal.IO.Zip.ZipArchive.GetFiles()
   at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
   at System.IO.Packaging.ZipPackage..ctor(String path, FileMode mode, FileAccess access, FileShare share, Boolean streaming)
   at System.IO.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess, FileShare packageShare, Boolean streaming)
   at System.IO.Packaging.Package.Open(String path, FileMode packageMode)

**Comment by emkaysri** [comment]
What was the solution for this error?
