### ISSUE TITLE
ThreadContext random fail with IndexOutOfRangeException

### ISSUE THREAD

**Issue by trivalik** [Microsoft/dotnet#890]
We use MessageFilter and today we comes up a random exception:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Windows.Forms.Application.ThreadContext.ProcessFilters(MSG& msg, Boolean& modified)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FPreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
```
In release notes from 4.6 is written that this is fixed (internal issue id [1072924]), but File Version of System.Windows.Forms.dll is 4.7.3163.0

We use Application.RemoveMessageFilter in Dispose method, which can be called by Finalizer.
Could this be the problem, when MessageFilter are not removed from GUI thread?

**Comment by Tanya-Solyanik** [comment]
Hi @trivalik  - we had shipped a fix to issues related to reentrancy in message filters in 4.6.1, see this code on reference source: https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/Application.cs,3546  where we added a re-entrance guard - `inProcessFilters`
This fix was considered breaking, thus it is activated only when application is retargeted to 4.6.1, or opts in into this change by adding 
```
<runtime>
    <!-- AppContextSwitchOverrides values are in the form of 'key1=true|false;key2=true|false  -->
    <AppContextSwitchOverrides value="Switch.System.Windows.Forms.DontSupportReentrantFilterMessage=false" />   
</runtime> 
```
to the app.config file. And application should run on the 4.6.1, or newer, Framework, available here:
https://www.microsoft.com/en-us/download/details.aspx?id=49982

More details: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/mitigation-custom-imessagefilter-prefiltermessage-implementations

**Comment by trivalik** [comment]
Thanks for this detailed information. Since this happens very seldom, I hope it will work.
