### ISSUE TITLE
UWP Cant Submit to store Error API FreeAddrInfoEx 

### ISSUE THREAD

**Issue by liliyashka** [Microsoft/dotnet#924]
I have installed the new update from nuget 6.2.2 and I get a certification error when the app is processing. Here is the result.
Supported APIs
Error Found: The supported APIs test detected the following errors:
API FreeAddrInfoEx in ws2_32.dll is not supported for this application type. myApp.dll calls this API.
Impact if not fixed: Using an API that is not part of the Windows SDK for Microsoft Store apps violates the Microsoft Store certification requirements.
How to fix: Review the error messages to identify the API that is not part of the Windows SDK for Microsoft Store apps. Please note, apps that are built in a debug configuration or without .NET Native enabled (where applicable) can fail this test as these environments may pull in unsupported APIs. Retest your app in a release configuration, and with .NET Native enabled if applicable. See the link below for more information:

**Comment by schuettecarsten** [comment]
Same problem for our app. Downgrading to v6.1.9 fixes this.

**Comment by MichalStrehovsky** [comment]
Thanks for bringing this to our attention and sorry for the trouble. This seems to be caused by a reference to this API being added in dotnet/corefx#26850. This was subsequently fixed to rely on the supported API in dotnet/corefx#29919 but that change didn't make it to the version of the framework UWP 6.2.2 shipped with. We'll look into addressing this problem.

**Comment by martinsuchan** [comment]
Is there any workaround to fix this issue, like updating specific .NET NuGet package? Or should we use `Microsoft.NETCore.UniversalWindowsPlatform 6.1.9` before this issue is fixed?

**Comment by shaishavbhatt08** [comment]
Have the same issue!

**Comment by Levvy055** [comment]
Also the same. And getting it on local cert tool

**Comment by shaishavbhatt08** [comment]
Use Microsoft.NETCore.UniversalWindowsPlatform 6.1.9, Next release will solve the issue i hope.

**Comment by shaishavbhatt08** [comment]
I submitted the app with  use Microsoft.NETCore.UniversalWindowsPlatform 6.1.9 and it did not fail

**Comment by erossetto** [comment]
I also had to downgrade... how is the nuget 6.2.2 not fixed or removed yet? This is causing devs to waste hours

**Comment by MichalStrehovsky** [comment]
> how is the nuget 6.2.2 not fixed or removed yet?

It was pulled down a couple days ago: 6.1.9 is the latest stable package: https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform

We are working on an update with a fix for this issue.

**Comment by MichalStrehovsky** [comment]
@yrest The 6.2.2 package is still unpublished: https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform. You shouldn't be offered to update to 6.2.2.

**Comment by LanceMcCarthy** [comment]
Weirdly enough, I had **6.2.3** installed today. I can't see how it got installed because the Package Manager doesn't list it :/

However, it will install if you manually enter the version number in your csproj, or use the Package Manager Console

`Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 6.2.3`

As proof it exists, here's the Librarie/io listing https://libraries.io/nuget/Microsoft.NETCore.UniversalWindowsPlatform

**Comment by LanceMcCarthy** [comment]
I just spoke to a few folks, don't use 6.2.3 unless you absolutely need support for ARM64. They still haven't fixed the underlying problem.

https://github.com/Microsoft/dotnet/issues/931#issuecomment-446713087

**Comment by yrest** [comment]
In a sense, all these are good things to learn and **try** to understand, I appreciate it, but from a user's perspective it's just a waste of time. :]
As soon as I update from 6.2.2 to 6.1.9 am getting weird exceptions, like following...
But when app is packaged using 6.2.2 it is being rejected by the store with subject.

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.ReadOnlySpan`1<Char> System.String.op_Implicit(System.String)'.
  Source=System.IO.FileSystem
  StackTrace:
   at System.IO.PathInternal.TrimEndingDirectorySeparator(String path)
   at System.IO.FileSystem.FillAttributeInfo(String path, WIN32_FILE_ATTRIBUTE_DATA& data, Boolean returnErrorOnNotFound)
   at System.IO.FileSystem.DirectoryExists(String path, Int32& lastError)
   at System.IO.Directory.Exists(String path)
   at …

Maybe it's a coincidence, but before I upgraded to 1809 at the end of November, all was good.

**Comment by yrest** [comment]
I must apologise for slightly misleading statements... Have restored back my original project and discovered that it was using 6.2.2 already for a while, meaning Microsoft.NETCore.UniversalWindowsPlatform has not been updated recently for me! 
It seems updating Xamarin.Forms to 3.4.0.1009999 causes confusion somewhere.

**Comment by yrest** [comment]
A month later same again - so so frustrating. 
Downgrading to 6.1.9 doesn't work for me anymore throwing errors on build.

Method 'WriteableBitmapImageBitmap.<Save>d__9.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
...
'PlatformModeDetector.<>c.<<SearchForAssembly>b__2_2>d.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder<string[]>.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.

etc etc
And it's nothing to do with Xamarin because everything builds, validates and runs on all sorts machines.

It is the freaking Store will not accept 6.2.2 for whatever reason. 
How hard could it be to keep up with own technology...

**Comment by nguyenquyhy** [comment]
> It is the freaking Store will not accept 6.2.2 for whatever reason.
> How hard could it be to keep up with own technology...

Microsoft acknowledged of the issue of 6.2.2 last December and promised a fix this year and it has been more than a month without any update. That's a huge disappointment!

If you really need 6.2.2 for your build, you can manually change the version to 6.2.3. Version 6.2.3 is hidden because it still has some issue (Microsoft doesn't really say what the issue is though).

I have published my app with 6.2.3 for a couple of weeks and so far I don't see any weird things. But your app might be different.

**Comment by EmilAlipiev** [comment]
> A month later same again - so so frustrating.
> Downgrading to 6.1.9 doesn't work for me anymore throwing errors on build.
> 
> Method 'WriteableBitmapImageBitmap.d__9.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
> ...
> 'PlatformModeDetector.<>c.<b__2_2>d.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder<string[]>.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
> 
> etc etc
> And it's nothing to do with Xamarin because everything builds, validates and runs on all sorts machines.
> 
> It is the freaking Store will not accept 6.2.2 for whatever reason.
> How hard could it be to keep up with own technology...

I have the same problem. did you find a solution for those errors? i get them only on release but it works on debug mode. please give an answer if you have found the reason. i wasted a lot of time about this s**

**Comment by LanceMcCarthy** [comment]
@EmilAlipiev You need to drop to 6.1.9 unless you explicitly need to target ARM64 and have an ARM64 package.  If you must distribute to ARM64 devices with an ARM64 package, then use 6.2.3.

Otherwise the normal ARM package will be fine

**Comment by EmilAlipiev** [comment]
@LanceMcCarthy  thanks for your quick answer but I am using 6.1.9 and those errors are returned for 6.1.9. I dont get how to fix them now.

here are all the errors I am getting
https://gist.githubusercontent.com/EmilAlipiev/9e14587b53173c02f292e0a18a0b3f5f/raw/0576b95823b8aa1ef2809a154ee81c3ee64853d0/gistfile1.txt

**Comment by LanceMcCarthy** [comment]
@EmilAlipiev There are other suspicious errors in there, for example, `Splat.WriteableBitmapImageBitmap` is being optimized out by the toolchain.

You can try to work around this by [including the Splat assemblies in the Runtime Directives](https://docs.microsoft.com/en-us/dotnet/framework/net-native/runtime-directives-rd-xml-configuration-file-reference), it might be worth taking [a quick read of how .NET Native works](https://docs.microsoft.com/en-us/dotnet/framework/net-native/getting-started-with-net-native) and why you can get errors when it strips out unreferenced code.

**Comment by EmilAlipiev** [comment]
@LanceMcCarthy  yes I have recognized it also. i wasnt sure if it is directly about splat but after checking my last working version from git history. i recognized that i was using older version of splat and already reported [here](https://github.com/reactiveui/Akavache/issues/462). it seems 6.1.9 version works fine for me now. thanks

**Comment by yrest** [comment]
@EmilAlipiev thanks to @nguyenquyhy editing csproj directly and simply changing 6.1.9 to 6.2.3 worked perfectly for me!

**Comment by Brandont990** [comment]
Has any one still have this problem with there app when they submit to the Windows Store. They are telling  me the app is crashing when i go to the setting page.

**Comment by LanceMcCarthy** [comment]
The 6.2.8 package is available now, update, clean and rebuild all the UWP packages with it and it will resolve this specific problem.

As far as the reason for your Settings Page crashing, that is most likely unrelated.

**Comment by Brandont990** [comment]
> 
> 
> The 6.2.8 package is available now, update, clean and rebuild all the UWP packages with it and it will resolve this specific problem.
> 
> As far as the reason for your Settings Page crashing, that is most likely unrelated.

Thank you I will give that a try.
